### ISSUE TITLE
Wrecking Ball (1984)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3459]
Tested on eXoDOS 5.1 Release.

On load the message about mapping keyboard keys from Caps Lock and Insert to "Z and X" is provided however only the "X" key seems to be working during the game. ie. you can only move the paddle to the right when playing the game and not to the left. The original controls of Caps Lock and Insert do not seem to be working either.

**Comment by SmilingSpectre** [comment]
Seems some problem with Z. I fixed it, deleting the mapping of key_z to Z. (thus it's "Caps Lock only" now).

**Comment by exoscoriae** [comment]
replaced mapper.

game seems unstable. It crash out on me twice during testing. Confirmed with ece as well. Drops to C: w/ no error message randomly.

**Comment by exoscoriae** [comment]
moving to low priority for now

**Comment by Python-Exoproject** [comment]
This is on Staging now. Does this resolve the reason the ticket was left open? The keyboard controls work with the mapper file we have created for Staging

**Comment by exoscoriae** [comment]
crashed on me within seconds.

moved to core=simple, and was able to play for over a minute.

still crashes though.

**Comment by Python-Exoproject** [comment]
Ive discovered that this is unofficial release of Bricks (1984) which is exactly the same game except for the title screen and shares the same issues. The ticket for Bricks is #4828 and as its the original game ill continue this on that ticket
